version: '3.8'

services:
  web-7.2:
    container_name: 'php7.0-projects'
    build:
      context: .
      dockerfile: ./php/7.2/Dockerfile
    ports:
      - "8082:80"
    volumes:
      - ../projects/7.2:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql-5.6

  web-8.0:
    container_name: 'php8.0-projects'
    build:
      context: .
      dockerfile: ./php/8.0/Dockerfile
    ports:
      - "8083:80"
    volumes:
      - ../projects/8.0:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql-8.0

  web-8.2:
    container_name: 'php8.2-projects'
    build:
      context: .
      dockerfile: ./php/8.2/Dockerfile
    ports:
      - "8084:80"
    volumes:
      - ../projects/8.2:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql-8.0

  web-8.3:
    container_name: 'php8.3-projects'
    build:
      context: .
      dockerfile: ./php/8.3/Dockerfile
    ports:
      - "8085:80"
    volumes:
      - ../projects/8.3:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql-8.0

  mysql-5.6:
    container_name: 'mysql-5.6'
    build:
      context: .
      dockerfile: ./mysql/5.6/Dockerfile
    ports:
      - "23307:3306"
    volumes:
      - mysql-data-5.6:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    networks:
      - app-network

  mysql-8.0:
    container_name: 'mysql-8.0'
    build:
      context: .
      dockerfile: ./mysql/8.0/Dockerfile
    ports:
      - "23308:3306"
    volumes:
      - mysql-data-8.0:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    networks:
      - app-network

volumes:
  mysql-data-5.6:
    driver: local
  mysql-data-8.0:
    driver: local

networks:
  app-network:
    driver: bridge
