
FROM mysql:8.0


ENV MYSQL_DATABASE=test_db \
    MYSQL_USER=dev \
    MYSQL_PASSWORD=dev \
    MYSQL_ROOT_PASSWORD=root


# COPY ./my.cnf /etc/mysql/conf.d/


EXPOSE 3306


# COPY ./init.sql /docker-entrypoint-initdb.d/
